// <auto-generated />
using BackFoodMacano.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackFoodMacano.Migrations
{
    [DbContext(typeof(FoodMacanoContext))]
    [Migration("20240906200737_inicioProyecto")]
    partial class inicioProyecto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BackFoodMacano.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Hamburguesas"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Sanguches"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Bebidas"
                        });
                });

            modelBuilder.Entity("BackFoodMacano.Models.DescripcionProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionCorta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescripcionLarga")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("descripcionProductos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescripcionCorta = "Clásica con queso",
                            DescripcionLarga = "Hamburguesa de carne a la parrilla con queso, lechuga, tomate y mayonesa."
                        },
                        new
                        {
                            Id = 2,
                            DescripcionCorta = "Sándwich de Milanesa",
                            DescripcionLarga = "Sándwich de milanesa con tomate, lechuga y mayonesa en pan francés."
                        },
                        new
                        {
                            Id = 3,
                            DescripcionCorta = "Coca-Cola",
                            DescripcionLarga = "Bebida gaseosa refrescante de 500 ml."
                        });
                });

            modelBuilder.Entity("BackFoodMacano.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Calidad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Calorias")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("DescripcionProductoId")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("DescripcionProductoId")
                        .IsUnique();

                    b.ToTable("productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calidad = "Alta",
                            Calorias = 300,
                            CategoriaId = 1,
                            DescripcionProductoId = 1,
                            ImagenUrl = "https://firebasestorage.googleapis.com/v0/b/foodmacano.appspot.com/o/img%2FHambuerguesa.png?alt=media&token=03b62ad8-16e4-4b06-b595-28baf10de9a7",
                            Nombre = "Hamburguesa Clásica",
                            Precio = 500
                        },
                        new
                        {
                            Id = 2,
                            Calidad = "Media",
                            Calorias = 350,
                            CategoriaId = 2,
                            DescripcionProductoId = 2,
                            ImagenUrl = "https://firebasestorage.googleapis.com/v0/b/foodmacano.appspot.com/o/img%2FMilanesa.png?alt=media&token=89683de5-6f3d-4a17-be75-be0640e5906b",
                            Nombre = "Sándwich de Milanesa",
                            Precio = 450
                        },
                        new
                        {
                            Id = 3,
                            Calidad = "Alta",
                            Calorias = 150,
                            CategoriaId = 3,
                            DescripcionProductoId = 3,
                            ImagenUrl = "https://firebasestorage.googleapis.com/v0/b/foodmacano.appspot.com/o/img%2FPiza.png?alt=media&token=d52e606d-597c-4065-aed3-9ae33e633ab8",
                            Nombre = "Coca-Cola 500ml",
                            Precio = 150
                        });
                });

            modelBuilder.Entity("BackFoodMacano.Models.Producto", b =>
                {
                    b.HasOne("BackFoodMacano.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackFoodMacano.Models.DescripcionProducto", "DescripcionProducto")
                        .WithOne("Producto")
                        .HasForeignKey("BackFoodMacano.Models.Producto", "DescripcionProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("DescripcionProducto");
                });

            modelBuilder.Entity("BackFoodMacano.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("BackFoodMacano.Models.DescripcionProducto", b =>
                {
                    b.Navigation("Producto");
                });
#pragma warning restore 612, 618
        }
    }
}
