# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - FoodMacano

on:
  push:
    branches:
      - main
    paths:
      - 'FoodMacanoWeb/**' # Solo ejecuta el flujo si hay cambios en esta carpeta
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Build FoodMacanoWeb project
        run: dotnet build FoodMacanoWeb/FoodMacanoWeb.csproj --configuration Release

      - name: Publish FoodMacanoWeb project
        run: dotnet publish FoodMacanoWeb/FoodMacanoWeb.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Esto es necesario para solicitar el JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2E1BF2FD97904D67A59FABBAE4095E14 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6A583797F583416E9B94DF656E88434E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F3C9047FB3AF48CEA9D2B2B7D4EC2E9E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FoodMacano'
          slot-name: 'Production'
          package: .
